# Generated by Django 4.2.7 on 2023-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yep_id', models.CharField(max_length=255, unique=True)),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_tickets', models.PositiveIntegerField(blank=True)),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(max_length=20)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
