# Generated by Django 4.2.7 on 2023-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('verification', models.FileField(upload_to='verification_files/')),
                ('verified', models.BooleanField(default=False)),
                ('college', models.CharField(max_length=255)),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
